### ISSUE TITLE
State File Static Name

### ISSUE THREAD

**Issue by CityHallin** [CityHallin/valheim_automated_deployment#22]
Currently the state file key from _backend.tf has it statically set to "terraform.tfstate". Need to update this to a dynamic name based on the project github per environment vars.PROJECT

**Comment by CityHallin** [comment]
Updated the backend.tf removing the state key entry and adding the Terraform Init backend config to add the state file info via the GitHub Vars. The is a strange issue with the haythem/public-ip task failing with what seems like a timeout in the northcentralus region. Udpated the variabled.tf to allow southcentralus region and will test with that to check. 

```
0s
Run haythem/public-ip@v[1](https://github.com/CityHallin/azure_cityhallin_dc/actions/runs/9879100231/job/27284553491#step:5:1).3
  with:
    maxRetries: 5
  env:
    ARM_CLIENT_ID: ***
    ARM_SUBSCRIPTION_ID: ***
    ARM_TENANT_ID: ***
    ```
